# Generated by Django 4.1.7 on 2023-03-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('lid', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('typeL', models.CharField(blank=True, max_length=15)),
                ('episodesL', models.CharField(blank=True, max_length=10)),
                ('timeadded', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
