# Generated by Django 4.1.7 on 2023-03-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_list_timeadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='typeL',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
