# Generated by Django 4.1.7 on 2023-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_list_typel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
