# Generated by Django 4.1.7 on 2023-03-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
