# Generated by Django 4.1.7 on 2023-03-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
