# Generated by Django 4.1.7 on 2023-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dateadded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='timeadded',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
