# Generated by Django 4.1.7 on 2023-03-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_list_dateadded_alter_list_timeadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='aid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
