# Generated by Django 4.1.7 on 2023-03-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_list_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='lid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
