# Generated by Django 4.1.7 on 2023-03-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0002_mediaanime'),
        ('users', '0012_alter_list_lid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='list',
            name='episodesL',
        ),
        migrations.RemoveField(
            model_name='list',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='list',
            name='typeL',
        ),
        migrations.AddField(
            model_name='list',
            name='media',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='animemaster.mediaanime'),
        ),
        migrations.AlterField(
            model_name='list',
            name='lid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
