# Generated by Django 4.1.7 on 2023-04-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_list_aid_remove_list_episodesl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user_status',
            field=models.CharField(default='Not Set', max_length=50, null=True),
        ),
    ]
