# Generated by Django 4.1.7 on 2023-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0003_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaanime',
            name='media_img',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='mediaanime',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
