# Generated by Django 4.1.7 on 2023-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0004_mediaanime_media_img_mediaanime_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaanime',
            name='media_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
