# Generated by Django 4.1.7 on 2023-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0005_alter_mediaanime_media_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaanime',
            name='media_img',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
