# Generated by Django 4.1.7 on 2023-04-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0007_alter_mediaanime_media_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaanime',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
