# Generated by Django 4.1.7 on 2023-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0008_alter_mediaanime_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaanime',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
