# Generated by Django 4.1.7 on 2023-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animemaster', '0009_mediaanime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaanime',
            name='status',
            field=models.CharField(blank=True, default='Not Set', max_length=100, null=True),
        ),
    ]
